### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cairo#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] #5
- [x] #7
- [x] #13
- [x] #75
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [x] #82
- [x] #81
- [x] #85

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!
