### ISSUE TITLE
Post-launch TODO

### ISSUE THREAD

**Issue by 0xNeshi** [exercism/cairo#96]
- [x] ~~write issues to shorten existing concepts~~ this will be done ad hoc
- [x] write issues to create concept exercises for each concept
- [x] ~~write issue to track new practice exercises creation~~ each practice exercise should have it's own tracking issue

**Comment by BNAndras** [comment]
I can start working on some of the #48in24 exercises that still need to be implemented.

**Comment by misicnenad** [comment]
@BNAndras go for it!
